// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Asset_ReadResult
    {
        public int AssetId { get; set; }
        public int ClientId { get; set; }
        [StringLength(50)]
        public string AssetType { get; set; }
        [Column("Value", TypeName = "decimal(18,2)")]
        public decimal Value { get; set; }
        [StringLength(200)]
        public string Provider { get; set; }
        public DateTime AsOf { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
