// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Client_Management_Database.Models;

public partial class Asset
{
    public int AssetId { get; set; }

    public int ClientId { get; set; }

    public string AssetType { get; set; }

    public decimal Value { get; set; }

    public string Provider { get; set; }

    public DateTime AsOf { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Client Client { get; set; }
}