// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Client_Management_Database.Models;
using Dapper;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Client_Management_Database.Models
{
    public partial class ClientManagementDemoContext
    {
        private IClientManagementDemoContextProcedures _procedures;

        public virtual IClientManagementDemoContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ClientManagementDemoContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IClientManagementDemoContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ClientManagementDemoContextProcedures : IClientManagementDemoContextProcedures
    {
        private readonly ClientManagementDemoContext _context;

        public ClientManagementDemoContextProcedures(ClientManagementDemoContext context)
        {
            _context = context;
        }

        public virtual async Task<int> __NormalizePagingAsync(OutputParameter<int?> pageNumber, OutputParameter<int?> pageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterPageNumber = new SqlParameter
            {
                ParameterName = "PageNumber",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = pageNumber?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterPageSize = new SqlParameter
            {
                ParameterName = "PageSize",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = pageSize?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterPageNumber,
                parameterPageSize,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[__NormalizePaging] @PageNumber = @PageNumber OUTPUT, @PageSize = @PageSize OUTPUT", sqlParameters, cancellationToken);

            pageNumber?.SetValue(parameterPageNumber.Value);
            pageSize?.SetValue(parameterPageSize.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Asset_CreateResult>> Asset_CreateAsync(int? clientId, string assetType, decimal? value, string provider, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "AssetType",
                    Size = 100,
                    Value = assetType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Value",
                    Precision = 18,
                    Scale = 2,
                    Value = value ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Provider",
                    Size = 400,
                    Value = provider ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Asset_CreateResult>("EXEC @returnValue = [dbo].[Asset_Create] @ClientId = @ClientId, @AssetType = @AssetType, @Value = @Value, @Provider = @Provider, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Asset_DeleteAsync(int? assetId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AssetId",
                    Value = assetId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Asset_Delete] @AssetId = @AssetId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Asset_ReadResult>> Asset_ReadAsync(int? assetId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AssetId",
                    Value = assetId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Asset_ReadResult>("EXEC @returnValue = [dbo].[Asset_Read] @AssetId = @AssetId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<(List<Asset_SearchResult1> Result1, List<Asset_SearchResult2> Result2)> Asset_SearchAsync(int? clientId, string assetType, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.ReturnValue,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "AssetType",
                    Size = 100,
                    Value = assetType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FromUtc",
                    Scale = 3,
                    Value = fromUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "ToUtc",
                    Scale = 3,
                    Value = toUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "PageNumber",
                    Value = pageNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SortBy",
                    Size = 100,
                    Value = sortBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SortDir",
                    Size = 8,
                    Value = sortDir ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };

            var dynamic = CreateDynamic(sqlParameters);
            (List<Asset_SearchResult1> Result1, List<Asset_SearchResult2> Result2)  _;

            using (var reader = await GetMultiReaderAsync(_context, dynamic, "[dbo].[Asset_Search]"))
            {
                _ = ((await reader.ReadAsync<Asset_SearchResult1>()).ToList(), (await reader.ReadAsync<Asset_SearchResult2>()).ToList());
            }

            returnValue?.SetValue(dynamic.Get<int>("returnValue"));

            return _;
        }

        public virtual async Task<List<Asset_UpdateResult>> Asset_UpdateAsync(int? assetId, string assetType, decimal? value, string provider, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AssetId",
                    Value = assetId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "AssetType",
                    Size = 100,
                    Value = assetType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Value",
                    Precision = 18,
                    Scale = 2,
                    Value = value ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Provider",
                    Size = 400,
                    Value = provider ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Asset_UpdateResult>("EXEC @returnValue = [dbo].[Asset_Update] @AssetId = @AssetId, @AssetType = @AssetType, @Value = @Value, @Provider = @Provider, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Client_CreateResult>> Client_CreateAsync(string firstName, string lastName, DateOnly? dateOfBirth, string email, string phone, int? statusLookupValueId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FirstName",
                    Size = 300,
                    Value = firstName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LastName",
                    Size = 300,
                    Value = lastName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DateOfBirth",
                    Value = dateOfBirth ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "Email",
                    Size = 508,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Phone",
                    Size = 60,
                    Value = phone ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "StatusLookupValueId",
                    Value = statusLookupValueId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Client_CreateResult>("EXEC @returnValue = [dbo].[Client_Create] @FirstName = @FirstName, @LastName = @LastName, @DateOfBirth = @DateOfBirth, @Email = @Email, @Phone = @Phone, @StatusLookupValueId = @StatusLookupValueId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Client_DeleteAsync(int? clientId, bool? force, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Force",
                    Value = force ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Client_Delete] @ClientId = @ClientId, @Force = @Force", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Client_ReadResult>> Client_ReadAsync(int? clientId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Client_ReadResult>("EXEC @returnValue = [dbo].[Client_Read] @ClientId = @ClientId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<(List<Client_SearchResult1> Result1, List<Client_SearchResult2> Result2)> Client_SearchAsync(string search, int? statusLookupValueId, DateOnly? dobFrom, DateOnly? dobTo, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.ReturnValue,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Search",
                    Size = 400,
                    Value = search ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "StatusLookupValueId",
                    Value = statusLookupValueId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DobFrom",
                    Value = dobFrom ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "DobTo",
                    Value = dobTo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "PageNumber",
                    Value = pageNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SortBy",
                    Size = 100,
                    Value = sortBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SortDir",
                    Size = 8,
                    Value = sortDir ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };

            var dynamic = CreateDynamic(sqlParameters);
            (List<Client_SearchResult1> Result1, List<Client_SearchResult2> Result2)  _;

            using (var reader = await GetMultiReaderAsync(_context, dynamic, "[dbo].[Client_Search]"))
            {
                _ = ((await reader.ReadAsync<Client_SearchResult1>()).ToList(), (await reader.ReadAsync<Client_SearchResult2>()).ToList());
            }

            returnValue?.SetValue(dynamic.Get<int>("returnValue"));

            return _;
        }

        public virtual async Task<List<Client_UpdateResult>> Client_UpdateAsync(int? clientId, string firstName, string lastName, DateOnly? dateOfBirth, string email, string phone, int? statusLookupValueId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FirstName",
                    Size = 300,
                    Value = firstName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LastName",
                    Size = 300,
                    Value = lastName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DateOfBirth",
                    Value = dateOfBirth ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "Email",
                    Size = 508,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Phone",
                    Size = 60,
                    Value = phone ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "StatusLookupValueId",
                    Value = statusLookupValueId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Client_UpdateResult>("EXEC @returnValue = [dbo].[Client_Update] @ClientId = @ClientId, @FirstName = @FirstName, @LastName = @LastName, @DateOfBirth = @DateOfBirth, @Email = @Email, @Phone = @Phone, @StatusLookupValueId = @StatusLookupValueId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<(List<Dashboard_ClientsByAge_BadResult1> Result1, List<Dashboard_ClientsByAge_BadResult2> Result2)> Dashboard_ClientsByAge_BadAsync(int? minAge, int? maxAge, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.ReturnValue,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MinAge",
                    Value = minAge ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MaxAge",
                    Value = maxAge ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };

            var dynamic = CreateDynamic(sqlParameters);
            (List<Dashboard_ClientsByAge_BadResult1> Result1, List<Dashboard_ClientsByAge_BadResult2> Result2)  _;

            using (var reader = await GetMultiReaderAsync(_context, dynamic, "[dbo].[Dashboard_ClientsByAge_Bad]"))
            {
                _ = ((await reader.ReadAsync<Dashboard_ClientsByAge_BadResult1>()).ToList(), (await reader.ReadAsync<Dashboard_ClientsByAge_BadResult2>()).ToList());
            }

            returnValue?.SetValue(dynamic.Get<int>("returnValue"));

            return _;
        }

        public virtual async Task<List<Dashboard_EstimatedNetWorth_BadResult>> Dashboard_EstimatedNetWorth_BadAsync(int? topN, DateOnly? minAsOfDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MinAsOfDate",
                    Value = minAsOfDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Dashboard_EstimatedNetWorth_BadResult>("EXEC @returnValue = [dbo].[Dashboard_EstimatedNetWorth_Bad] @TopN = @TopN, @MinAsOfDate = @MinAsOfDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Dashboard_StaleClients_BadResult>> Dashboard_StaleClients_BadAsync(int? days, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Days",
                    Value = days ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Dashboard_StaleClients_BadResult>("EXEC @returnValue = [dbo].[Dashboard_StaleClients_Bad] @Days = @Days", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Dashboard_StatusBreakdown_BadResult>> Dashboard_StatusBreakdown_BadAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Dashboard_StatusBreakdown_BadResult>("EXEC @returnValue = [dbo].[Dashboard_StatusBreakdown_Bad]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Expenditure_CreateResult>> Expenditure_CreateAsync(int? clientId, string category, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Category",
                    Size = 100,
                    Value = category ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AmountMonthly",
                    Precision = 18,
                    Scale = 2,
                    Value = amountMonthly ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Expenditure_CreateResult>("EXEC @returnValue = [dbo].[Expenditure_Create] @ClientId = @ClientId, @Category = @Category, @AmountMonthly = @AmountMonthly, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Expenditure_DeleteAsync(int? expenditureId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ExpenditureId",
                    Value = expenditureId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Expenditure_Delete] @ExpenditureId = @ExpenditureId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Expenditure_ReadResult>> Expenditure_ReadAsync(int? expenditureId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ExpenditureId",
                    Value = expenditureId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Expenditure_ReadResult>("EXEC @returnValue = [dbo].[Expenditure_Read] @ExpenditureId = @ExpenditureId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<(List<Expenditure_SearchResult1> Result1, List<Expenditure_SearchResult2> Result2)> Expenditure_SearchAsync(int? clientId, string category, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.ReturnValue,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Category",
                    Size = 100,
                    Value = category ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FromUtc",
                    Scale = 3,
                    Value = fromUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "ToUtc",
                    Scale = 3,
                    Value = toUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "PageNumber",
                    Value = pageNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SortBy",
                    Size = 100,
                    Value = sortBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SortDir",
                    Size = 8,
                    Value = sortDir ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };

            var dynamic = CreateDynamic(sqlParameters);
            (List<Expenditure_SearchResult1> Result1, List<Expenditure_SearchResult2> Result2)  _;

            using (var reader = await GetMultiReaderAsync(_context, dynamic, "[dbo].[Expenditure_Search]"))
            {
                _ = ((await reader.ReadAsync<Expenditure_SearchResult1>()).ToList(), (await reader.ReadAsync<Expenditure_SearchResult2>()).ToList());
            }

            returnValue?.SetValue(dynamic.Get<int>("returnValue"));

            return _;
        }

        public virtual async Task<List<Expenditure_UpdateResult>> Expenditure_UpdateAsync(int? expenditureId, string category, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ExpenditureId",
                    Value = expenditureId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Category",
                    Size = 100,
                    Value = category ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AmountMonthly",
                    Precision = 18,
                    Scale = 2,
                    Value = amountMonthly ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Expenditure_UpdateResult>("EXEC @returnValue = [dbo].[Expenditure_Update] @ExpenditureId = @ExpenditureId, @Category = @Category, @AmountMonthly = @AmountMonthly, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Income_CreateResult>> Income_CreateAsync(int? clientId, string source, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Source",
                    Size = 100,
                    Value = source ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AmountMonthly",
                    Precision = 18,
                    Scale = 2,
                    Value = amountMonthly ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Income_CreateResult>("EXEC @returnValue = [dbo].[Income_Create] @ClientId = @ClientId, @Source = @Source, @AmountMonthly = @AmountMonthly, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Income_DeleteAsync(int? incomeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IncomeId",
                    Value = incomeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Income_Delete] @IncomeId = @IncomeId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Income_ReadResult>> Income_ReadAsync(int? incomeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IncomeId",
                    Value = incomeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Income_ReadResult>("EXEC @returnValue = [dbo].[Income_Read] @IncomeId = @IncomeId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<(List<Income_SearchResult1> Result1, List<Income_SearchResult2> Result2)> Income_SearchAsync(int? clientId, string source, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.ReturnValue,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Source",
                    Size = 100,
                    Value = source ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FromUtc",
                    Scale = 3,
                    Value = fromUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "ToUtc",
                    Scale = 3,
                    Value = toUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "PageNumber",
                    Value = pageNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SortBy",
                    Size = 100,
                    Value = sortBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SortDir",
                    Size = 8,
                    Value = sortDir ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };

            var dynamic = CreateDynamic(sqlParameters);
            (List<Income_SearchResult1> Result1, List<Income_SearchResult2> Result2)  _;

            using (var reader = await GetMultiReaderAsync(_context, dynamic, "[dbo].[Income_Search]"))
            {
                _ = ((await reader.ReadAsync<Income_SearchResult1>()).ToList(), (await reader.ReadAsync<Income_SearchResult2>()).ToList());
            }

            returnValue?.SetValue(dynamic.Get<int>("returnValue"));

            return _;
        }

        public virtual async Task<List<Income_UpdateResult>> Income_UpdateAsync(int? incomeId, string source, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IncomeId",
                    Value = incomeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Source",
                    Size = 100,
                    Value = source ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AmountMonthly",
                    Precision = 18,
                    Scale = 2,
                    Value = amountMonthly ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Income_UpdateResult>("EXEC @returnValue = [dbo].[Income_Update] @IncomeId = @IncomeId, @Source = @Source, @AmountMonthly = @AmountMonthly, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Journal_CreateResult>> Journal_CreateAsync(int? clientId, int? noteTypeLookupValueId, DateTime? occurredAt, string body, string author, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NoteTypeLookupValueId",
                    Value = noteTypeLookupValueId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OccurredAt",
                    Scale = 3,
                    Value = occurredAt ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "Body",
                    Size = -1,
                    Value = body ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Author",
                    Size = 200,
                    Value = author ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Journal_CreateResult>("EXEC @returnValue = [dbo].[Journal_Create] @ClientId = @ClientId, @NoteTypeLookupValueId = @NoteTypeLookupValueId, @OccurredAt = @OccurredAt, @Body = @Body, @Author = @Author", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Journal_DeleteAsync(int? journalId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "JournalId",
                    Value = journalId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Journal_Delete] @JournalId = @JournalId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Journal_ReadResult>> Journal_ReadAsync(int? journalId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "JournalId",
                    Value = journalId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Journal_ReadResult>("EXEC @returnValue = [dbo].[Journal_Read] @JournalId = @JournalId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<(List<Journal_SearchResult1> Result1, List<Journal_SearchResult2> Result2)> Journal_SearchAsync(int? clientId, int? noteTypeLookupValueId, DateTime? fromUtc, DateTime? toUtc, string search, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.ReturnValue,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NoteTypeLookupValueId",
                    Value = noteTypeLookupValueId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "FromUtc",
                    Scale = 3,
                    Value = fromUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "ToUtc",
                    Scale = 3,
                    Value = toUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "Search",
                    Size = 800,
                    Value = search ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PageNumber",
                    Value = pageNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SortBy",
                    Size = 100,
                    Value = sortBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SortDir",
                    Size = 8,
                    Value = sortDir ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };

            var dynamic = CreateDynamic(sqlParameters);
            (List<Journal_SearchResult1> Result1, List<Journal_SearchResult2> Result2)  _;

            using (var reader = await GetMultiReaderAsync(_context, dynamic, "[dbo].[Journal_Search]"))
            {
                _ = ((await reader.ReadAsync<Journal_SearchResult1>()).ToList(), (await reader.ReadAsync<Journal_SearchResult2>()).ToList());
            }

            returnValue?.SetValue(dynamic.Get<int>("returnValue"));

            return _;
        }

        public virtual async Task<List<Journal_UpdateResult>> Journal_UpdateAsync(int? journalId, int? noteTypeLookupValueId, DateTime? occurredAt, string body, string author, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "JournalId",
                    Value = journalId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NoteTypeLookupValueId",
                    Value = noteTypeLookupValueId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OccurredAt",
                    Scale = 3,
                    Value = occurredAt ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "Body",
                    Size = -1,
                    Value = body ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Author",
                    Size = 200,
                    Value = author ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Journal_UpdateResult>("EXEC @returnValue = [dbo].[Journal_Update] @JournalId = @JournalId, @NoteTypeLookupValueId = @NoteTypeLookupValueId, @OccurredAt = @OccurredAt, @Body = @Body, @Author = @Author", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Liability_CreateResult>> Liability_CreateAsync(int? clientId, string liabilityType, decimal? balance, decimal? rate, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "LiabilityType",
                    Size = 100,
                    Value = liabilityType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Balance",
                    Precision = 18,
                    Scale = 2,
                    Value = balance ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Rate",
                    Precision = 9,
                    Scale = 4,
                    Value = rate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Liability_CreateResult>("EXEC @returnValue = [dbo].[Liability_Create] @ClientId = @ClientId, @LiabilityType = @LiabilityType, @Balance = @Balance, @Rate = @Rate, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Liability_DeleteAsync(int? liabilityId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "LiabilityId",
                    Value = liabilityId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Liability_Delete] @LiabilityId = @LiabilityId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Liability_ReadResult>> Liability_ReadAsync(int? liabilityId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "LiabilityId",
                    Value = liabilityId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Liability_ReadResult>("EXEC @returnValue = [dbo].[Liability_Read] @LiabilityId = @LiabilityId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<(List<Liability_SearchResult1> Result1, List<Liability_SearchResult2> Result2)> Liability_SearchAsync(int? clientId, string liabilityType, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.ReturnValue,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClientId",
                    Value = clientId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "LiabilityType",
                    Size = 100,
                    Value = liabilityType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FromUtc",
                    Scale = 3,
                    Value = fromUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "ToUtc",
                    Scale = 3,
                    Value = toUtc ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "PageNumber",
                    Value = pageNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SortBy",
                    Size = 100,
                    Value = sortBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SortDir",
                    Size = 8,
                    Value = sortDir ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };

            var dynamic = CreateDynamic(sqlParameters);
            (List<Liability_SearchResult1> Result1, List<Liability_SearchResult2> Result2)  _;

            using (var reader = await GetMultiReaderAsync(_context, dynamic, "[dbo].[Liability_Search]"))
            {
                _ = ((await reader.ReadAsync<Liability_SearchResult1>()).ToList(), (await reader.ReadAsync<Liability_SearchResult2>()).ToList());
            }

            returnValue?.SetValue(dynamic.Get<int>("returnValue"));

            return _;
        }

        public virtual async Task<List<Liability_UpdateResult>> Liability_UpdateAsync(int? liabilityId, string liabilityType, decimal? balance, decimal? rate, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "LiabilityId",
                    Value = liabilityId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "LiabilityType",
                    Size = 100,
                    Value = liabilityType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Balance",
                    Precision = 18,
                    Scale = 2,
                    Value = balance ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Rate",
                    Precision = 9,
                    Scale = 4,
                    Value = rate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "AsOf",
                    Scale = 3,
                    Value = asOf ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Liability_UpdateResult>("EXEC @returnValue = [dbo].[Liability_Update] @LiabilityId = @LiabilityId, @LiabilityType = @LiabilityType, @Balance = @Balance, @Rate = @Rate, @AsOf = @AsOf", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<LookupValue_SearchResult>> LookupValue_SearchAsync(string lookupCode, bool? onlyActive, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "LookupCode",
                    Size = 200,
                    Value = lookupCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OnlyActive",
                    Value = onlyActive ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<LookupValue_SearchResult>("EXEC @returnValue = [dbo].[LookupValue_Search] @LookupCode = @LookupCode, @OnlyActive = @OnlyActive", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        private static DynamicParameters CreateDynamic(SqlParameter[] sqlParameters)
        {
            var dynamic = new DynamicParameters();
            foreach (var sqlParameter in sqlParameters)
            {
                dynamic.Add(sqlParameter.ParameterName, sqlParameter.Value, sqlParameter.DbType, sqlParameter.Direction, sqlParameter.Size, sqlParameter.Precision, sqlParameter.Scale);
            }

            return dynamic;
        }

        private async Task<SqlMapper.GridReader> GetMultiReaderAsync(DbContext db, DynamicParameters dynamic, string sql)
        {
            IDbTransaction tran = null;
            if (db.Database.CurrentTransaction is IDbContextTransaction ctxTran)
            {
                tran = ctxTran.GetDbTransaction();
            }

            return await ((IDbConnection)db.Database.GetDbConnection())
                .QueryMultipleAsync(sql, dynamic, tran, db.Database.GetCommandTimeout(), CommandType.StoredProcedure);
        }
    }
}
