// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Client_Management_Database.Models;

public partial class ClientManagementDemoContext : DbContext
{
    public ClientManagementDemoContext()
    {
    }

    public ClientManagementDemoContext(DbContextOptions<ClientManagementDemoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Asset> Assets { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Expenditure> Expenditures { get; set; }

    public virtual DbSet<Income> Incomes { get; set; }

    public virtual DbSet<Journal> Journals { get; set; }

    public virtual DbSet<Liability> Liabilities { get; set; }

    public virtual DbSet<Lookup> Lookups { get; set; }

    public virtual DbSet<LookupValue> LookupValues { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Asset>(entity =>
        {
            entity.HasKey(e => e.AssetId).HasName("PK__Asset__4349235266929250");

            entity.ToTable("Asset");

            entity.HasIndex(e => new { e.ClientId, e.AsOf }, "IX_Asset_Client_AsOf").IsDescending(false, true);

            entity.Property(e => e.AsOf)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.AssetType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Provider).HasMaxLength(200);
            entity.Property(e => e.Value).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Client).WithMany(p => p.Assets)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Asset__ClientId__6754599E");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Client__E67E1A24DD1B86B1");

            entity.ToTable("Client");

            entity.HasIndex(e => new { e.LastName, e.FirstName }, "IX_Client_Name");

            entity.HasIndex(e => e.StatusLookupValueId, "IX_Client_Status");

            entity.HasIndex(e => e.Email, "UX_Client_Email")
                .IsUnique()
                .HasFilter("([Email] IS NOT NULL)");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Email).HasMaxLength(254);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Phone).HasMaxLength(30);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.StatusLookupValue).WithMany(p => p.Clients)
                .HasForeignKey(d => d.StatusLookupValueId)
                .HasConstraintName("FK__Client__StatusLo__68487DD7");
        });

        modelBuilder.Entity<Expenditure>(entity =>
        {
            entity.HasKey(e => e.ExpenditureId).HasName("PK__Expendit__5C07CEBDE7141742");

            entity.ToTable("Expenditure");

            entity.HasIndex(e => new { e.ClientId, e.AsOf }, "IX_Expenditure_Client_AsOf").IsDescending(false, true);

            entity.Property(e => e.AmountMonthly).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.AsOf)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Client).WithMany(p => p.Expenditures)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Expenditu__Clien__693CA210");
        });

        modelBuilder.Entity<Income>(entity =>
        {
            entity.HasKey(e => e.IncomeId).HasName("PK__Income__60DFC60C85C78793");

            entity.ToTable("Income");

            entity.HasIndex(e => new { e.ClientId, e.AsOf }, "IX_Income_Client_AsOf").IsDescending(false, true);

            entity.Property(e => e.AmountMonthly).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.AsOf)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Client).WithMany(p => p.Incomes)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Income__ClientId__6A30C649");
        });

        modelBuilder.Entity<Journal>(entity =>
        {
            entity.HasKey(e => e.JournalId).HasName("PK__Journal__250103E68CCB5752");

            entity.ToTable("Journal");

            entity.HasIndex(e => new { e.ClientId, e.OccurredAt }, "IX_Journal_Client_OccurredAt").IsDescending(false, true);

            entity.Property(e => e.Author).HasMaxLength(100);
            entity.Property(e => e.Body).IsRequired();
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.OccurredAt).HasPrecision(3);

            entity.HasOne(d => d.Client).WithMany(p => p.Journals)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Journal__ClientI__6B24EA82");

            entity.HasOne(d => d.NoteTypeLookupValue).WithMany(p => p.Journals)
                .HasForeignKey(d => d.NoteTypeLookupValueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Journal__NoteTyp__6C190EBB");
        });

        modelBuilder.Entity<Liability>(entity =>
        {
            entity.HasKey(e => e.LiabilityId).HasName("PK__Liabilit__A84A1312A0440DFE");

            entity.ToTable("Liability");

            entity.HasIndex(e => new { e.ClientId, e.AsOf }, "IX_Liability_Client_AsOf").IsDescending(false, true);

            entity.Property(e => e.AsOf)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.LiabilityType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Rate).HasColumnType("decimal(9, 4)");

            entity.HasOne(d => d.Client).WithMany(p => p.Liabilities)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Liability__Clien__6D0D32F4");
        });

        modelBuilder.Entity<Lookup>(entity =>
        {
            entity.HasKey(e => e.LookupId).HasName("PK__Lookup__6D8B9C4BAFA2380A");

            entity.ToTable("Lookup");

            entity.HasIndex(e => e.Code, "UX_Lookup_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<LookupValue>(entity =>
        {
            entity.HasKey(e => e.LookupValueId).HasName("PK__LookupVa__BFA1132C7EC4BDA9");

            entity.ToTable("LookupValue");

            entity.HasIndex(e => new { e.LookupId, e.SortOrder }, "IX_LookupValue_Lookup_Sort");

            entity.HasIndex(e => new { e.LookupId, e.Code }, "UX_LookupValue_Lookup_Code").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Lookup).WithMany(p => p.LookupValues)
                .HasForeignKey(d => d.LookupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LookupVal__Looku__6E01572D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}