// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Client_CreateResult
    {
        public int ClientId { get; set; }
        [StringLength(150)]
        public string FirstName { get; set; }
        [StringLength(150)]
        public string LastName { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        [StringLength(254)]
        public string Email { get; set; }
        [StringLength(30)]
        public string Phone { get; set; }
        public int? StatusLookupValueId { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
