// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Client_SearchResult2
    {
        public int? TotalCount { get; set; }
    }
}
