// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Dashboard_StatusBreakdown_BadResult
    {
        [StringLength(200)]
        public string StatusLabel { get; set; }
        public int? ClientCount { get; set; }
    }
}
