// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Dashboard_ClientsByAge_BadResult1
    {
        public int ClientId { get; set; }
        [StringLength(150)]
        public string FirstName { get; set; }
        [StringLength(150)]
        public string LastName { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        [Column("AgeYears", TypeName = "decimal(18,0)")]
        public decimal? AgeYears { get; set; }
        [StringLength(5)]
        public string AgeBand { get; set; }
    }
}
