// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Dashboard_EstimatedNetWorth_BadResult
    {
        public int ClientId { get; set; }
        [StringLength(150)]
        public string FirstName { get; set; }
        [StringLength(150)]
        public string LastName { get; set; }
        [Column("EstimatedNetWorth", TypeName = "decimal(38,2)")]
        public decimal? EstimatedNetWorth { get; set; }
        [Column("TotalMonthlyIncome", TypeName = "decimal(38,2)")]
        public decimal TotalMonthlyIncome { get; set; }
    }
}
