// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Client_Management_Database.Models;
using Dapper;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Client_Management_Database.Models
{
    public partial interface IClientManagementDemoContextProcedures
    {
        Task<int> __NormalizePagingAsync(OutputParameter<int?> pageNumber, OutputParameter<int?> pageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Asset_CreateResult>> Asset_CreateAsync(int? clientId, string assetType, decimal? value, string provider, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Asset_DeleteAsync(int? assetId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Asset_ReadResult>> Asset_ReadAsync(int? assetId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Asset_SearchResult1> Result1, List<Asset_SearchResult2> Result2)> Asset_SearchAsync(int? clientId, string? assetType, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Asset_UpdateResult>> Asset_UpdateAsync(int? assetId, string assetType, decimal? value, string provider, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Client_CreateResult>> Client_CreateAsync(string firstName, string lastName, DateOnly? dateOfBirth, string email, string phone, int? statusLookupValueId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Client_DeleteAsync(int? clientId, bool? force, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Client_ReadResult>> Client_ReadAsync(int? clientId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Client_SearchResult1> Result1, List<Client_SearchResult2> Result2)> Client_SearchAsync(string search, int? statusLookupValueId, DateOnly? dobFrom, DateOnly? dobTo, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Client_UpdateResult>> Client_UpdateAsync(int? clientId, string firstName, string lastName, DateOnly? dateOfBirth, string email, string phone, int? statusLookupValueId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Dashboard_ClientsByAge_BadResult1> Result1, List<Dashboard_ClientsByAge_BadResult2> Result2)> Dashboard_ClientsByAge_BadAsync(int? minAge, int? maxAge, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Dashboard_EstimatedNetWorth_BadResult>> Dashboard_EstimatedNetWorth_BadAsync(int? topN, DateOnly? minAsOfDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Dashboard_StaleClients_BadResult>> Dashboard_StaleClients_BadAsync(int? days, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Dashboard_StatusBreakdown_BadResult>> Dashboard_StatusBreakdown_BadAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Expenditure_CreateResult>> Expenditure_CreateAsync(int? clientId, string category, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Expenditure_DeleteAsync(int? expenditureId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Expenditure_ReadResult>> Expenditure_ReadAsync(int? expenditureId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Expenditure_SearchResult1> Result1, List<Expenditure_SearchResult2> Result2)> Expenditure_SearchAsync(int? clientId, string category, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Expenditure_UpdateResult>> Expenditure_UpdateAsync(int? expenditureId, string category, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Income_CreateResult>> Income_CreateAsync(int? clientId, string source, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Income_DeleteAsync(int? incomeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Income_ReadResult>> Income_ReadAsync(int? incomeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Income_SearchResult1> Result1, List<Income_SearchResult2> Result2)> Income_SearchAsync(int? clientId, string source, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Income_UpdateResult>> Income_UpdateAsync(int? incomeId, string source, decimal? amountMonthly, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Journal_CreateResult>> Journal_CreateAsync(int? clientId, int? noteTypeLookupValueId, DateTime? occurredAt, string body, string author, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Journal_DeleteAsync(int? journalId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Journal_ReadResult>> Journal_ReadAsync(int? journalId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Journal_SearchResult1> Result1, List<Journal_SearchResult2> Result2)> Journal_SearchAsync(int? clientId, int? noteTypeLookupValueId, DateTime? fromUtc, DateTime? toUtc, string search, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Journal_UpdateResult>> Journal_UpdateAsync(int? journalId, int? noteTypeLookupValueId, DateTime? occurredAt, string body, string author, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Liability_CreateResult>> Liability_CreateAsync(int? clientId, string liabilityType, decimal? balance, decimal? rate, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Liability_DeleteAsync(int? liabilityId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Liability_ReadResult>> Liability_ReadAsync(int? liabilityId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Liability_SearchResult1> Result1, List<Liability_SearchResult2> Result2)> Liability_SearchAsync(int? clientId, string liabilityType, DateTime? fromUtc, DateTime? toUtc, int? pageNumber, int? pageSize, string sortBy, string sortDir, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Liability_UpdateResult>> Liability_UpdateAsync(int? liabilityId, string liabilityType, decimal? balance, decimal? rate, DateTime? asOf, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LookupValue_SearchResult>> LookupValue_SearchAsync(string lookupCode, bool? onlyActive, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
