// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Income_CreateResult
    {
        public int IncomeId { get; set; }
        public int ClientId { get; set; }
        [StringLength(50)]
        public string Source { get; set; }
        [Column("AmountMonthly", TypeName = "decimal(18,2)")]
        public decimal AmountMonthly { get; set; }
        public DateTime AsOf { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
