// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Journal_UpdateResult
    {
        public int JournalId { get; set; }
        public int ClientId { get; set; }
        public int NoteTypeLookupValueId { get; set; }
        public DateTime OccurredAt { get; set; }
        [StringLength(2147483647)]
        public string Body { get; set; }
        [StringLength(100)]
        public string Author { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
