// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Client_Management_Database.Models;

public partial class Journal
{
    public int JournalId { get; set; }

    public int ClientId { get; set; }

    public int NoteTypeLookupValueId { get; set; }

    public DateTime OccurredAt { get; set; }

    public string Body { get; set; }

    public string Author { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Client Client { get; set; }

    public virtual LookupValue NoteTypeLookupValue { get; set; }
}