// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Client_Management_Database.Models;

public partial class Liability
{
    public int LiabilityId { get; set; }

    public int ClientId { get; set; }

    public string LiabilityType { get; set; }

    public decimal Balance { get; set; }

    public decimal? Rate { get; set; }

    public DateTime AsOf { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Client Client { get; set; }
}