// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class Liability_CreateResult
    {
        public int LiabilityId { get; set; }
        public int ClientId { get; set; }
        [StringLength(50)]
        public string LiabilityType { get; set; }
        [Column("Balance", TypeName = "decimal(18,2)")]
        public decimal Balance { get; set; }
        [Column("Rate", TypeName = "decimal(9,4)")]
        public decimal? Rate { get; set; }
        public DateTime AsOf { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
