// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Client_Management_Database.Models;

public partial class LookupValue
{
    public int LookupValueId { get; set; }

    public int LookupId { get; set; }

    public string Code { get; set; }

    public string Label { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    public virtual ICollection<Journal> Journals { get; set; } = new List<Journal>();

    public virtual Lookup Lookup { get; set; }
}