// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Client_Management_Database.Models
{
    public partial class LookupValue_SearchResult
    {
        public int LookupValueId { get; set; }
        public int LookupId { get; set; }
        [StringLength(100)]
        public string Code { get; set; }
        [StringLength(200)]
        public string Label { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
