//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagementWebforms
{


    public partial class Client
    {

        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;

        protected global::System.Web.UI.WebControls.TextBox txtFirst;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirst;

        protected global::System.Web.UI.WebControls.TextBox txtLast;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLast;

        protected global::System.Web.UI.WebControls.TextBox txtDob;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.Panel pnlRelated;

        protected global::System.Web.UI.WebControls.DropDownList ddlNoteType;

        protected global::System.Web.UI.WebControls.TextBox txtJournalBody;

        protected global::System.Web.UI.WebControls.TextBox txtJournalAuthor;

        protected global::System.Web.UI.WebControls.Button btnAddJournal;

        protected global::System.Web.UI.WebControls.GridView gvJournal;

        protected global::System.Web.UI.WebControls.TextBox txtAssetType;

        protected global::System.Web.UI.WebControls.TextBox txtAssetValue;

        protected global::System.Web.UI.WebControls.TextBox txtAssetProvider;

        protected global::System.Web.UI.WebControls.Button btnAddAsset;

        protected global::System.Web.UI.WebControls.GridView gvAssets;

        protected global::System.Web.UI.WebControls.TextBox txtLiabType;

        protected global::System.Web.UI.WebControls.TextBox txtLiabBalance;

        protected global::System.Web.UI.WebControls.TextBox txtLiabRate;

        protected global::System.Web.UI.WebControls.Button btnAddLiab;

        protected global::System.Web.UI.WebControls.GridView gvLiabilities;

        protected global::System.Web.UI.WebControls.TextBox txtIncomeSource;

        protected global::System.Web.UI.WebControls.TextBox txtIncomeAmount;

        protected global::System.Web.UI.WebControls.Button btnAddIncome;

        protected global::System.Web.UI.WebControls.GridView gvIncome;

        protected global::System.Web.UI.WebControls.TextBox txtExCat;

        protected global::System.Web.UI.WebControls.TextBox txtExAmt;

        protected global::System.Web.UI.WebControls.Button btnAddEx;

        protected global::System.Web.UI.WebControls.GridView gvExpenditure;
    }
}

