//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagementWebforms
{


    public partial class Dashboard
    {

        protected global::System.Web.UI.WebControls.Button btnRefreshStatus;

        protected global::System.Web.UI.WebControls.GridView gvStatus;

        protected global::System.Web.UI.WebControls.Label lblDays;

        protected global::System.Web.UI.WebControls.TextBox txtDays;

        protected global::System.Web.UI.WebControls.Button btnRefreshStale;

        protected global::System.Web.UI.WebControls.GridView gvStale;

        protected global::System.Web.UI.WebControls.Label lblTopN;

        protected global::System.Web.UI.WebControls.TextBox txtTopN;

        protected global::System.Web.UI.WebControls.Label lblMinAsOf;

        protected global::System.Web.UI.WebControls.TextBox txtMinAsOf;

        protected global::System.Web.UI.WebControls.Button btnRefreshNetWorth;

        protected global::System.Web.UI.WebControls.GridView gvNetWorth;

        protected global::System.Web.UI.WebControls.Label lblMinAge;

        protected global::System.Web.UI.WebControls.TextBox txtMinAge;

        protected global::System.Web.UI.WebControls.Label lblMaxAge;

        protected global::System.Web.UI.WebControls.TextBox txtMaxAge;

        protected global::System.Web.UI.WebControls.Button btnRefreshAge;

        protected global::System.Web.UI.WebControls.GridView gvAgeDetail;

        protected global::System.Web.UI.WebControls.GridView gvAgeBands;
    }
}

